"""create_table_prova

Revision ID: 40279a8fe2d4
Revises: 
Create Date: 2021-06-05 15:22:48.535308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40279a8fe2d4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prova',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('data', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pergunta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('prova', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['prova'], ['prova.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('opcao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('correta', sa.Boolean(), nullable=False),
    sa.Column('pergunta', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pergunta'], ['pergunta.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resposta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pergunta', sa.Integer(), nullable=False),
    sa.Column('opcao', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['opcao'], ['opcao.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pergunta'], ['pergunta.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resposta')
    op.drop_table('opcao')
    op.drop_table('pergunta')
    op.drop_table('prova')
    # ### end Alembic commands ###
