"""add_urole

Revision ID: a4b99a6fc851
Revises: 5da2f7dbca15
Create Date: 2021-06-26 16:08:19.422329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4b99a6fc851'
down_revision = '5da2f7dbca15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('urole', sa.String(length=50), server_default='user', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'urole')
    # ### end Alembic commands ###
