"""add_valor_prova

Revision ID: ad45f3266c8b
Revises: 40279a8fe2d4
Create Date: 2021-06-06 22:03:58.218100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad45f3266c8b'
down_revision = '40279a8fe2d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pergunta', sa.Column('valor', sa.Integer(), nullable=True))
    op.add_column('prova', sa.Column('valor', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prova', 'valor')
    op.drop_column('pergunta', 'valor')
    # ### end Alembic commands ###
